### **What is Tensor**
##### **Tensor is like a Numpy nD array. So you can represents anything in 1D, 2D, 3D or higher dimensions using tensor.**

**Characteristics of Tensor:**
   * works with nd-array
   * GPU support
   * Computational graph / Backpropagation
   * Tensor is Immutable - means, you cannot change any tensor, but can create a new tensor

### **Let's Start**

#### **Create Tensor**

In [15]:
#Create a tensor
import tensorflow as tf

# create the tensor
x = tf.constant(5)  # single scaler value- 5

# We can also add shape and data type
x = tf.constant(5, shape=(1,1), dtype=tf.float32)

# Rank-1 Tensor: Create a 1D tensor
x = tf.constant([1,2,3,4,5])
# Rank-2 Tensor: Create a 2D tensor
x = tf.constant([[1,2,3],[4,5,6]])

# Create a automatic tensor
x = tf.ones((3,3))
# Default data type is float. You can specify the datatype
x = tf.ones((3,3), dtype=tf.int32)
# Other automatic tensors
x= tf.zeros(3,3)
# Diagonal Metrics
x = tf.eye(3)   #It takes only one parameter
# Random values tensor
x = tf.random.normal((3,3), mean=0, stddev=1)   #You have to identify mean and standard deviation with dimension
# Uniform tensor: where you can specify the range of values
#x = tf.random.uniform((3,3), minval=0, maxval=1)
x = tf.random.uniform((3,3), minval=1, maxval=2)
print(x)

tf.Tensor(
[[1.3427515 1.652445  1.9550549]
 [1.646282  1.2395786 1.8771622]
 [1.8226774 1.3475649 1.0995827]], shape=(3, 3), dtype=float32)
