### **What is Tensor**
##### **Tensor is like a Numpy nD array. So you can represents anything in 1D, 2D, 3D or higher dimensions using tensor.**

**Characteristics of Tensor:**
   * works with nd-array
   * GPU support
   * Computational graph / Backpropagation
   * Tensor is Immutable - means, you cannot change any tensor, but can create a new tensor

### **Let's Start**

##### **Create Tensor**

In [2]:
#Create a tensor
import tensorflow as tf

# create the tensor
x0 = tf.constant(5)  # single scaler value- 5

# We can also add shape and data type
x1 = tf.constant(5, shape=(1,1), dtype=tf.float32)

# Rank-1 Tensor: Create a 1D tensor
x2 = tf.constant([1,2,3,4,5])
x3 = tf.range(10)

# Rank-2 Tensor: Create a 2D tensor
x4 = tf.constant([[1,2,3],[4,5,6]])
# Create a automatic tensor
x5 = tf.ones((3,3))
# Default data type is float. You can specify the datatype
x6 = tf.ones((3,3), dtype=tf.int32)
# Other automatic tensors
x7 = tf.zeros(3,3)
# Diagonal Metrics
x8 = tf.eye(3)   #It takes only one parameter
# Random values tensor
x9 = tf.random.normal((3,3), mean=0, stddev=1)   #You have to identify mean and standard deviation with dimension
# Uniform tensor: where you can specify the range of values
#x10 = tf.random.uniform((3,3), minval=0, maxval=1)
x10 = tf.random.uniform((3,3), minval=1, maxval=2)
print(x10)

tf.Tensor(
[[1.8326489 1.1087914 1.4324548]
 [1.7153082 1.3018728 1.7764101]
 [1.2971876 1.7202747 1.2832543]], shape=(3, 3), dtype=float32)


##### **Cast Tensor**
###### **Casting means- changing the data type**

In [3]:
x0 = tf.range(10)   #By default it is int32 type
x0 = tf.cast(x0, dtype=tf.float32)
print(x0)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


##### **Operations on Tensor**

**Elementwise Operation**

In [21]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

# Addition
#z = tf.add(x,y)
z = x + y

# Subtraction
#z = tf.subtract(x,y)
z = x - y

# Multiplication
#z = tf.multiply(x,y)
z = x * y

# Division
z = tf.divide(x,y)
#z = x / y

# Dot Product
# What dot do? It multiply elementwise and then add all the results of multiplication
z = tf.tensordot(x, y, axes=1)   #You have to define axes here

# Exponential Operation - kind of power operation
z = x ** 3

print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


**Matrices Multiplication**

In [22]:
# For matrices operation, the column number of the first tensor must match the row number of the second tensor
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

#z = tf.matmul(x, y)
z = x @ y

print(z)

tf.Tensor(
[[-0.4869185 -3.336775  -2.1208951 -1.4827483]
 [-3.0643272 -5.0712867  5.1564956 -1.6461035]], shape=(2, 4), dtype=float32)


**Slicing, Indexing**

In [37]:
x = tf.constant([[1,2,3,4], [6,7,8,9]])
print(x, "\n")

# Accessing the list    * Indexing starts from 0
print(x[0])     # 1st row
print(x[0][0])  # 1st row 1st element
print(x[0][2])  # 1st row 3rd element
print(x[0][-1]) # 1st row last element

print(x[:, 0])      # 1st column of the tensor
print(x[0, :])      # 1st row of the tensor
print(x[0, 1:3])    # 1st row's 2nd and 3rd element. [1=Starting point and 3=Ending point]
print(x[1, 2:3])    # 2nd row's 3rd element  [Ending point will be excluded]
print(x[0, 1])      # 1st row 2nd element

tf.Tensor(
[[1 2 3 4]
 [6 7 8 9]], shape=(2, 4), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 6], shape=(2,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


**Reshaping**